version: '3.9'
services:
  mysql-spring-boot:
    image: mysql:latest
    container_name: mysql-spring-boot
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_USER=devuser
      - MYSQL_PASSWORD=123456
      - MYSQL_DATABASE=test_db
    ports:
      - '3309:3306'
    volumes:
      - mysql-spring-boot:/var/lib/mysql
volumes:
  mysql-spring-boot:
